### ISSUE TITLE
Cannot connect to postgresql running local on MacOS

### ISSUE THREAD

**Issue by dimdin** [microsoft/pgtoolsservice#210]
- MacOS 10.13.6
- PostgreSQL 11.2 listening on 127.0.0.1:5432 (installed with homebrew)
- Azure Data Studio 1.5.1

I am trying to connect to the local PostgreSQL and following messages are displayed:

[Error - XXX] Connection to server got closed. Server will not be restarted.
[Error - XXX] Request connection/connect failed.
Error: Connection got disposed.
	at Object.dispose (/Users/XXX/.azuredatastudio/extensions/microsoft.azuredatastudio-postgresql-0.1.0/node_modules/vscode-jsonrpc/lib/main.js:825:25)
	at Object.dispose (/Users/XXX/.azuredatastudio/extensions/microsoft.azuredatastudio-postgresql-0.1.0/node_modules/vscode-languageclient/lib/client.js:57:35)
	at SqlOpsDataClient.handleConnectionClosed (/Users/XXX/.azuredatastudio/extensions/microsoft.azuredatastudio-postgresql-0.1.0/node_modules/vscode-languageclient/lib/client.js:1864:38)
	at SqlOpsDataClient.handleConnectionClosed (/Users/XXX/.azuredatastudio/extensions/microsoft.azuredatastudio-postgresql-0.1.0/node_modules/vscode-languageclient/lib/main.js:106:15)
	at closeHandler (/Users/XXX/.azuredatastudio/extensions/microsoft.azuredatastudio-postgresql-0.1.0/node_modules/vscode-languageclient/lib/client.js:1852:18)
	at CallbackList.invoke (/Users/XXX/.azuredatastudio/extensions/microsoft.azuredatastudio-postgresql-0.1.0/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/XXX/.azuredatastudio/extensions/microsoft.azuredatastudio-postgresql-0.1.0/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at closeHandler (/Users/XXX/.azuredatastudio/extensions/microsoft.azuredatastudio-postgresql-0.1.0/node_modules/vscode-jsonrpc/lib/main.js:221:26)
	at CallbackList.invoke (/Users/XXX/.azuredatastudio/extensions/microsoft.azuredatastudio-postgresql-0.1.0/node_modules/vscode-jsonrpc/lib/events.js:71:39)
	at Emitter.fire (/Users/XXX/.azuredatastudio/extensions/microsoft.azuredatastudio-postgresql-0.1.0/node_modules/vscode-jsonrpc/lib/events.js:135:36)
	at StreamMessageWriter.AbstractMessageWriter.fireClose (/Users/XXX/.azuredatastudio/extensions/microsoft.azuredatastudio-postgresql-0.1.0/node_modules/vscode-jsonrpc/lib/messageWriter.js:57:27)
	at Socket.<anonymous> (/Users/XXX/.azuredatastudio/extensions/microsoft.azuredatastudio-postgresql-0.1.0/node_modules/vscode-jsonrpc/lib/messageWriter.js:79:63)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at Pipe.Socket._destroy.cb._handle.close [as _onclose] (net.js:554:12)

**Comment by akamath46297** [comment]
@dimdin we are looking into PG11 issues holistically. We will do a consolidated effort to release PG11 fixes in our subsequent release.

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of PostgreSQL extension v0.4.1. Please reopen if issue persists, thank you.
