### ISSUE TITLE
No module named 'pgsqltoolsservice.language.completion.packages'

### ISSUE THREAD

**Issue by ixe013** [microsoft/pgtoolsservice#220]
Running Azure Data Studio 1.12.1 (user install):

```
Version: 1.12.1 (user setup)
Commit: cccb9327c707fe71de24d5ce655acb29cc8946d1
Date: 2019-10-07T21:49:53.568Z
VS Code 1.37.0
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.16299
```

I searched for the Postgres extension and enabled it. Azure Data Studio tells me it is installed:

```
Name: PostgreSQL
Id: microsoft.azuredatastudio-postgresql
Description: PostgreSQL extension for Azure Data Studio
Version: 0.2.2
Publisher: Microsoft
VS Marketplace Link: undefined?itemName=Microsoft.azuredatastudio-postgresql
```

But when it installed (and everytime I restart Azure Data Studio), I get this error:

```
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 14, in run
  File "C:\hostedtoolcache\windows\Python\3.6.8\x64\lib\site-packages\cx_Freeze\initscripts\Console.py", line 26, in run
  File "pgsqltoolsservice/pgtoolsservice_main.py", line 18, in <module>
  File "D:\a\1\s\pgsqltoolsservice\language\__init__.py", line 6, in <module>
  File "D:\a\1\s\pgsqltoolsservice\language\language_service.py", line 32, in <module>
  File "D:\a\1\s\pgsqltoolsservice\language\completion\__init__.py", line 6, in <module>
  File "D:\a\1\s\pgsqltoolsservice\language\completion\pgcompleter.py", line 20, in <module>
ModuleNotFoundError: No module named 'pgsqltoolsservice.language.completion.packages'
[Error - 3:51:27 p.m.] Connection to server got closed. Server will not be restarted.
```

Although the connection type Postgres now shows, it just loops forever trying to connect. I can connect just fine usign `psql` or `HeidiSQL`.

**Comment by nasc17** [comment]
![image](https://github.com/microsoft/pgtoolsservice/assets/69922333/1f919137-b127-4c7b-89a0-02db34c76c23)
