### ISSUE TITLE
ImportError: libffi.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ibuda** [microsoft/pgtoolsservice#278]
Hi,

I am getting this error when trying to install PostgreSQL extension:
```
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
```

More details:
```
It seems the debugger cannot resolve /opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/posixpath.py
This may make the debugger miss breakpoints in the standard library.
Related bug: https://bugs.python.org/issue1180193
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "ossdbtoolsservice/ossdbtoolsservice_main.py", line 11, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ptvsd/__init__.py", line 13, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ptvsd/_vendored/force_pydevd.py", line 37, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ptvsd/_vendored/__init__.py", line 123, in preimport
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/importlib/__init__.py", line 126, in import_module
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/pydevd.py", line 31, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/_pydevd_bundle/pydevd_utils.py", line 8, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/ctypes/__init__.py", line 7, in <module>
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
[Error - 11:11:22 AM] Connection to server got closed. Server will not be restarted.
```

OS: Ubuntu 20.04.1 LTS
Azure Data Studio:  Version: 1.25.1
Commit: e7eacc32c0d20bd4da843320c3bfac231b308c98
Date: 2020-12-11T01:51:41.708Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-58-generic

Any help or guidance is much appreciated. Thank you.

**Comment by ibuda** [comment]
this [solution](https://stackoverflow.com/questions/61875869/ubuntu-20-04-upgrade-python-missing-libffi-so-6/63329830#63329830) worked for me.

**Comment by FabulousMuller** [comment]
> this [solution](https://stackoverflow.com/questions/61875869/ubuntu-20-04-upgrade-python-missing-libffi-so-6/63329830#63329830) worked for me.

For me too. But before that I had to chmod ~/.azuredatastudio/extensions/microsoft.azuredatastudio-postgresql-0.2.7/out/ossdbtoolsservice/Linux/v1.5.0/pgsqltoolsservice/ossdbtoolsservice_main to +777 because it wasn't  -x (?) in Ubuntu Focal fossa.

**Comment by superdalton** [comment]
> this [solution](https://stackoverflow.com/questions/61875869/ubuntu-20-04-upgrade-python-missing-libffi-so-6/63329830#63329830) worked for me.

this worked for me a great deal. thank you

**Comment by baybal** [comment]
@ibuda please don't close the issue. The underlying problem is still there.

**Comment by ibuda** [comment]
@baybal Hi, I closed the issue since I found and shared the solution to it.

**Comment by dorianmariefr** [comment]
Getting the latest ffi from github worked for me, e.g.:

```ruby
gem "ffi", github: "ffi/ffi"
```

in my `Gemfile`

**Comment by pravin** [comment]
symlinking to another version isn't the best way of solving the issue though. Do the devs have other ideas?

**Comment by GaryHopeMS** [comment]
Reopening issue as underlying problem still remains.

**Comment by fantasy-fish** [comment]
> this [solution](https://stackoverflow.com/questions/61875869/ubuntu-20-04-upgrade-python-missing-libffi-so-6/63329830#63329830) worked for me.

The link in the solution is no longer valid
