### ISSUE TITLE
Error on AzureDataStudio startup after installing PostgreSQL extension on Linux Mint

### ISSUE THREAD

**Issue by shifu137** [microsoft/pgtoolsservice#282]
Hi,
After installing the PostgreSQL extension on AzureDataStudio, I'm getting this error.
My setup is:
OS: Linux Mint 20.1 Ulyssa (Xfce Edition)
Installed AzureDataStudio as a deb package.

```
It seems the debugger cannot resolve /opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/posixpath.py
This may make the debugger miss breakpoints in the standard library.
Related bug: https://bugs.python.org/issue1180193
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "ossdbtoolsservice/ossdbtoolsservice_main.py", line 11, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ptvsd/__init__.py", line 13, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ptvsd/_vendored/force_pydevd.py", line 37, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ptvsd/_vendored/__init__.py", line 123, in preimport
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/importlib/__init__.py", line 126, in import_module
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/pydevd.py", line 31, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/_pydevd_bundle/pydevd_utils.py", line 8, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/ctypes/__init__.py", line 7, in <module>
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
[Error - 10:58:21 am] Connection to server got closed. Server will not be restarted.

```

Do let me know if you need more information.

**Comment by shifu137** [comment]
Looks like duplicate of #280 
Sorry, closing this one out.

**Comment by sgryphon** [comment]
Appears to be a duplicate of https://github.com/microsoft/pgtoolsservice/issues/218 and should be closed.

They have the same error, a dialog that pops up on start and says _"OSS DB Tools Service component exited unexpectedly. Please restart Azure Data Studio."_, then an error reported in the output section:

```
"It seems the debugger cannot resolve /opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/posixpath.py
This may make the debugger miss breakpoints in the standard library.
Related bug: https://bugs.python.org/issue1180193
... a stack trace ...
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
[Error - 12:57:17 PM] Connection to server got closed. Server will not be restarted."
```

The important bit is the missing "libffi.so.6"

There are many other duplicates (that should probably be closed as well)

https://github.com/microsoft/pgtoolsservice/issues/239
https://github.com/microsoft/pgtoolsservice/issues/251
https://github.com/microsoft/pgtoolsservice/issues/275
https://github.com/microsoft/pgtoolsservice/issues/279
https://github.com/microsoft/pgtoolsservice/issues/280
https://github.com/microsoft/pgtoolsservice/issues/282
https://github.com/microsoft/pgtoolsservice/issues/283

**Work around:**

So far, the workaround for some systems linking libffi.so.6 to version 7 seems to work:
 
```
sudo ln -s libffi.so.7 /usr/lib/x86_64-linux-gnu/libffi.so.6
```

The workaround does not work if you only have version 8, e.g. Ubuntu 20.10 -- it gets past the first error but then just fails. You can check which version you have via:

```
ls -la /usr/lib/x86_64-linux-gnu/libffi*
```

The other workaround is to directly install the version 6 libraries directly:

```
curl -o libffi6_3.2.1-8_amd64.deb http://mirrors.kernel.org/ubuntu/pool/main/libf/libffi/libffi6_3.2.1-8_amd64.deb
sudo apt install ./libffi6_3.2.1-8_amd64.deb
```

**Comment by tyoc213** [comment]
@sgryphon patching libffi.so.6 using .7 is OK on ubuntu, the only problem missing is that it seems only normal query page work, the notebook not as in this image

![image](https://user-images.githubusercontent.com/506234/148295548-49fcda7a-1545-458a-84a2-1c134cf05ca4.png)

See that it says 10 rows, but it doesn't show any row at all, only in the query editor

![image](https://user-images.githubusercontent.com/506234/148295653-73770b3f-e8ac-4285-a222-e90aa61d654a.png)
