### ISSUE TITLE
PostgreSQL in Azure Data Studio has a trouble

### ISSUE THREAD

**Issue by leonardo-nicolas** [microsoft/pgtoolsservice#299]
I use Data Studio in Ubuntu 20.04.3 LTS, and, When I open Data Studio, I got a message on Exit Console:

It seems the debugger cannot resolve /opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/posixpath.py
This may make the debugger miss breakpoints in the standard library.
Related bug: https://bugs.python.org/issue1180193
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "ossdbtoolsservice/ossdbtoolsservice_main.py", line 11, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ptvsd/__init__.py", line 13, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ptvsd/_vendored/force_pydevd.py", line 37, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ptvsd/_vendored/__init__.py", line 123, in preimport
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/importlib/__init__.py", line 126, in import_module
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/pydevd.py", line 31, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/_pydevd_bundle/pydevd_utils.py", line 8, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/ctypes/__init__.py", line 7, in <module>
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
[Error - 01:10:27] Connection to server got closed. Server will not be restarted.

With PostgreSQL, I'm having this trouble described above. I tried to fix this issue searching on Stackoverflow, Reddit or searching...
But, not in SQL Server! It's OK!
Please, can Anyone help me?

**Comment by pravin** [comment]
I have the same issue. The python path is incorrect. I think ADS looks for Python 3.6.12 in the /opt path.

**Comment by leonardon397** [comment]
I've changed from Ubuntu 20.04 to Fedora 35, to learn some things that is almost same on RHEL and CentOS...
I don't know why, but, I didn't have this trouble ao usar o Fedora 35! I'm asking to myself "what the f**** hell? Ubuntu 20.04 does't works and in Fedora 35, works... holy s***!". Sorry for the profanity and innapropriate words!

I checked that Fedora 35 comes with last python version (3.10) and I've installed PG 14 from official repositorie, got on official postgre website (I've configured to ignore any versions of PG, come from Fedora repositories). I didn't installed another python version. On Ubuntu 20.04, I installed python 3.10 and I did somes changes, to pip work firstly python 3.10 instead of another versions. I don't know if this change that I did on Ubuntu, was cause to got this trouble.


But, before open this issue, I seen these python files, on vim and nano, but I didn't have free time to debug the python script. But, in my case, these files existed...

**Comment by hironico** [comment]
In the message log it says : 
ImportError: libffi.so.6: cannot open shared object file: No such file or directory

See #218 

and resolution proposed here : https://github.com/microsoft/pgtoolsservice/issues/283#issuecomment-905194188

`curl -o libffi6_3.2.1-8_amd64.deb http://mirrors.kernel.org/ubuntu/pool/main/libf/libffi/libffi6_3.2.1-8_amd64.deb`

and then

`sudo apt install ./libffi6_3.2.1-8_amd64.deb`

this issue should be closed ?

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of PostgreSQL extension v0.4.1. Please reopen if issue persists, thank you.
