### ISSUE TITLE
Bug in Linux

### ISSUE THREAD

**Issue by amarantei64** [microsoft/pgtoolsservice#308]
I'm using Fedora and when installing the extension it gives me the following error.

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "ossdbtoolsservice/ossdbtoolsservice_main.py", line 11, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ptvsd/__init__.py", line 13, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ptvsd/_vendored/force_pydevd.py", line 37, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ptvsd/_vendored/__init__.py", line 123, in preimport
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/importlib/__init__.py", line 126, in import_module
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/pydevd.py", line 31, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/_pydevd_bundle/pydevd_utils.py", line 8, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/ctypes/__init__.py", line 7, in <module>
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
[Error - 11:40:49 p. m.] Connection to server got closed. Server will not be restarted.

**Comment by xerscot** [comment]
Same on Ubuntu 20.04:

It seems the debugger cannot resolve /opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/posixpath.py
This may make the debugger miss breakpoints in the standard library.
Related bug: https://bugs.python.org/issue1180193
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "ossdbtoolsservice/ossdbtoolsservice_main.py", line 11, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ptvsd/__init__.py", line 13, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ptvsd/_vendored/force_pydevd.py", line 37, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ptvsd/_vendored/__init__.py", line 123, in preimport
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/importlib/__init__.py", line 126, in import_module
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/pydevd.py", line 31, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/_pydevd_bundle/pydevd_utils.py", line 8, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/ctypes/__init__.py", line 7, in <module>
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
[Error - 17:41:03] Connection to server got closed. Server will not be restarted.

**Comment by ricsdeol** [comment]
Hi same problem here:

DISTRIB_ID=Pop
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Pop!_OS 22.04 LTS"

DISTRIB_ID=Pop
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Pop!_OS 22.04 LTS"

➜ azuredatastudio --version
1.37.0
d904740d93d7df76a0ba361f20e4351813b57645
x64


```
It seems the debugger cannot resolve /opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/posixpath.py
This may make the debugger miss breakpoints in the standard library.
Related bug: https://bugs.python.org/issue1180193
[Error - 4:24:49 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by khofesh** [comment]
I have the same problem.
Fedora 36, GNOME 42 + wayland.


Python version installed: Python 3.10.5

```shell
It seems the debugger cannot resolve /opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/posixpath.py
This may make the debugger miss breakpoints in the standard library.
Related bug: https://bugs.python.org/issue1180193
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "ossdbtoolsservice/ossdbtoolsservice_main.py", line 11, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ptvsd/__init__.py", line 13, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ptvsd/_vendored/force_pydevd.py", line 37, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ptvsd/_vendored/__init__.py", line 123, in preimport
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/importlib/__init__.py", line 126, in import_module
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/pydevd.py", line 31, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/_pydevd_bundle/pydevd_utils.py", line 8, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/ctypes/__init__.py", line 7, in <module>
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
[Error - 7:26:52 PM] Connection to server got closed. Server will not be restarted.
```

the error indicates python `3.6.12`, does this mean we need to build the the extension against the python 3.10.5 ?

**Comment by khofesh** [comment]
installing libffi3.1 on Fedora 36 fixed the problem

```shell
sudo dnf install libffi3.1
```

**Comment by Wilfison** [comment]
See [#322](https://github.com/microsoft/pgtoolsservice/issues/322#issuecomment-1329137327)

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of PostgreSQL extension v0.4.1. Please reopen if issue persists, thank you.
