### ISSUE TITLE
error occurred when I try to install postgreSQL  extension

### ISSUE THREAD

**Issue by joe032022** [microsoft/pgtoolsservice#322]
```py
It seems the debugger cannot resolve /opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/posixpath.py
This may make the debugger miss breakpoints in the standard library.
Related bug: https://bugs.python.org/issue1180193
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "ossdbtoolsservice/ossdbtoolsservice_main.py", line 11, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ptvsd/__init__.py", line 13, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ptvsd/_vendored/force_pydevd.py", line 37, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/ptvsd/_vendored/__init__.py", line 123, in preimport
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/importlib/__init__.py", line 126, in import_module
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/pydevd.py", line 31, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/_pydevd_bundle/pydevd_utils.py", line 8, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/ctypes/__init__.py", line 7, in <module>
ImportError: libffi.so.6: cannot open shared object file: No such file or directory
[Error - 9:25:12 am] Connection to server got closed. Server will not be restarted.

```

**Comment by joeljohn2022** [comment]
Also I can across a lot of error when I try to install SQL server 2019

**Comment by GetAHat** [comment]
I'm on Fedora 36, so i was able to use _dnf whatprovides_. In, again, Fedora the package you need to install is _libffi3.1-3.1-32.fc36.x86_64_ but I believe there should be something similar on any modern distro

**Comment by Wilfison** [comment]
I had the same issue on Ubuntu and derivatives. You need to install the `libffi6` library manually.

You can do this by downloading the official ubuntu repository file from the link below.

https://packages.ubuntu.com/bionic/amd64/libffi6/download

Follow the steps below to avoid any problems.

- Uninstall the postgres extension;
- Close the software you are trying to install;
- Install `libff6`;
- Open the software;
- Install the extension again;
- Wait 15 or 20 seconds for installation to complete in the background;

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of PostgreSQL extension v0.4.1. Please reopen if issue persists, thank you.
