### ISSUE TITLE
"OSS DB Tools Service component exited unexpectedly. Please restart Azure Data Studio" on Arch Linux

### ISSUE THREAD

**Issue by jhonrocha** [microsoft/pgtoolsservice#357]
I have fixed this on my local. I had to install `libxcrypt-compat`. 
The traceback on my local was:
```
❯ cat .config/azuredatastudio/logs/20230404T110300/exthost1/output_logging_20230404T110303/6-ossdbToolsService.log
It seems the debugger cannot resolve /opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/posixpath.py
This may make the debugger miss breakpoints in the standard library.
Related bug: https://bugs.python.org/issue1180193
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 40, in run
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 37, in run
  File "ossdbtoolsservice/ossdbtoolsservice_main.py", line 13, in <module>
  File "/home/vsts/work/1/s/ossdbtoolsservice/admin/__init__.py", line 6, in <module>
  File "/home/vsts/work/1/s/ossdbtoolsservice/admin/admin_service.py", line 8, in <module>
  File "/home/vsts/work/1/s/ossdbtoolsservice/connection/__init__.py", line 6, in <module>
  File "/home/vsts/work/1/s/ossdbtoolsservice/connection/connection_service.py", line 29, in <module>
  File "/home/vsts/work/1/s/ossdbtoolsservice/driver/__init__.py", line 6, in <module>
  File "/home/vsts/work/1/s/ossdbtoolsservice/driver/types/__init__.py", line 7, in <module>
  File "/home/vsts/work/1/s/ossdbtoolsservice/driver/types/psycopg_driver.py", line 8, in <module>
  File "/opt/hostedtoolcache/Python/3.6.12/x64/lib/python3.6/site-packages/psycopg2/__init__.py", line 50, in <module>
ImportError: libcrypt.so.1: cannot open shared object file: No such file or directory
[Error - 11:03:04 AM] Connection to server got closed. Server will not be restarted.

```

**Comment by csaltos** [comment]
I've got a similar error with Debian 11 ... anyway, good try Microsoft, try harder :sweat:

**Comment by matrs** [comment]
@jhonrocha ,  This problem has to do with the ABI version of  `libffi`, it needs version **6**. See which version you have installed:  `ls -la /usr/lib/libffi*` .  If that's your problem,  from Aur you can  install  `libffi6` .

This should work for any linux distribution without `libffi6`.

**Comment by nasc17** [comment]
Bug has been addressed in latest stable release of pgtoolsservice extension v1.8.0. Please reopen if issue persists, thank you.
